### ISSUE TITLE
Division By Zero

### ISSUE THREAD

**Issue by eMerzh** [grantjenks/python_runstats#1]
Hi, i'm not a math expert, but i'm trying to compute regression of  a serie of points
but got division by zero....

here is an excerpt of the points that make it crash
```
>>> r = Regression([(0.6875, 0.7578947368421053), (0.6875, 0.8105263157894737)])
>>> r.slope()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python2.7/site-packages/runstats.py", line 216, in slope
    return self._sxy / sxx
ZeroDivisionError: float division by zero
```

**Comment by eMerzh** [comment]
ooh.... juste saw that all points does have the same x... 
might be the cause... right ?

**Comment by grantjenks** [comment]
Yep. Slope is rise over run and your run is zero.
